[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  DATABASE_URL = "postgresql://builder_user:builder_pass@localhost:5432/builder_forecasting_dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
