[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.2"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
